import React from "react";

const EscortRateEdit = ({
  rateClass,
  formData,
  handleChange,
  setFormData,
  currency,
}) => {
  const handleCheck = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.checked });
  };

  return (
    <div className={`bg-[#1E1E1E] ${rateClass} rounded-xl pb-8 py-5 px-7`}>
      <h2 className="md:text-2xl text-[18px] text-white font-semibold">Rate</h2>
      <label className="text-white pt-5 flex flex-col" htmlFor="ethnicity">
        <span className="font-semibold text-[14px] md:text-base pb-1">
          Currency<span className="text-[#E9CB50]">*</span>
        </span>
        <div className=" placeholder-[#102127] bg-[#F0F2F5] text-[#102127] rounded-xl outline-none px-4">
          <select
            className="w-[100%] bg-[#F0F2F5] py-[10px] md:py-[14px] outline-none"
            name="currency"
            id="currency"
            value={currency}
            onChange={handleChange}
          >
            <option value="">Choose Here</option>
            <option>{currency}</option>
          </select>
        </div>
      </label>
      {/* <div className="text-white flex pt-10 items-center">
        <label className="checkContainer w-[50%] ">
          Incall
          <input
            onChange={handleCheck}
            type="checkbox"
            name="available_incall"
            checked={formData.available_incall}
          />
          <span className="checkmate"></span>
        </label>

        <label className="checkContainer  w-[50%]">
          Outcall
          <input
            onChange={handleCheck}
            checked={formData.available_outcall}
            type="checkbox"
            name="available_outcall"
          />
          <span className="checkmate"></span>
        </label>
      </div> */}

      <div>
        <h2 className="pb-3 pt-6 font-semibold text-[18px] text-white">
          Outcall Rates
        </h2>
        <div className="grid text-white md:grid-cols-3 gap-5">
          <label htmlFor="outcall_short_time">
            <p className="py-2 font-semibold">Hourly Rate</p>
            <div className=" placeholder-[#102127] bg-[#F0F2F5] text-[#102127] rounded-xl outline-none px-4">
              <select
                className="w-[100%] bg-[#F0F2F5] py-[10px] md:py-[14px] outline-none"
                name="outcall_short_time"
                id="outcall_short_time"
                value={formData.outcall_short_time}
                onChange={handleChange}
              >
                <option value="">Choose here</option>
                <option>1</option>
                <option>10</option>
                <option>100</option>
                <option>1000</option>
                <option>10000</option>
                <option>100000</option>
                <option>1000000</option>
                <option>15</option>
                <option>150</option>
                <option>1500</option>
                <option>15000</option>
                <option>150000</option>
                <option>1500000</option>
                <option>2</option>
                <option>20</option>
                <option>200</option>
                <option>2000</option>
                <option>20000</option>
                <option>200000</option>
                <option>2000000</option>
                <option>25</option>
                <option>250</option>
                <option>2500</option>
                <option>25000</option>
                <option>250000</option>
                <option>2500000</option>
                <option>3</option>
                <option>30</option>
                <option>300</option>
                <option>3000</option>
                <option>30000</option>
                <option>300000</option>
                <option>3000000</option>
                <option>35</option>
                <option>350</option>
                <option>3500</option>
                <option>35000</option>
                <option>350000</option>
                <option>3500000</option>
                <option>4</option>
                <option>40</option>
                <option>400</option>
                <option>4000</option>
                <option>40000</option>
                <option>400000</option>
                <option>4000000</option>
                <option>45</option>
                <option>450</option>
                <option>4500</option>
                <option>45000</option>
                <option>450000</option>
                <option>4500000</option>
                <option>5</option>
                <option>50</option>
                <option>500</option>
                <option>5000</option>
                <option>50000</option>
                <option>500000</option>
                <option>5000000</option>
                <option>55</option>
                <option>550</option>
                <option>5500</option>
                <option>55000</option>
                <option>550000</option>
                <option>5500000</option>
                <option>6</option>
                <option>60</option>
                <option>600</option>
                <option>6000</option>
                <option>60000</option>
                <option>600000</option>
                <option>6000000</option>
                <option>65</option>
                <option>650</option>
                <option>6500</option>
                <option>65000</option>
                <option>650000</option>
                <option>6500000</option>
                <option>7</option>
                <option>70</option>
                <option>700</option>
                <option>7000</option>
                <option>70000</option>
                <option>700000</option>
                <option>7000000</option>
                <option>75</option>
                <option>750</option>
                <option>7500</option>
                <option>75000</option>
                <option>750000</option>
                <option>7500000</option>
                <option>8</option>
                <option>80</option>
                <option>800</option>
                <option>8000</option>
                <option>80000</option>
                <option>800000</option>
                <option>8000000</option>
                <option>85</option>
                <option>850</option>
                <option>8500</option>
                <option>85000</option>
                <option>850000</option>
                <option>8500000</option>
                <option>9</option>
                <option>90</option>
                <option>900</option>
                <option>9000</option>
                <option>90000</option>
                <option>900000</option>
                <option>9000000</option>
                <option>95</option>
                <option>950</option>
                <option>9500</option>
                <option>95000</option>
                <option>950000</option>
                <option>9500000</option>
              </select>
            </div>
          </label>
          <label htmlFor="outcall_overnight">
            <p className="py-2 font-semibold">One Night</p>
            <div className=" placeholder-[#102127] bg-[#F0F2F5] text-[#102127] rounded-xl outline-none px-4">
              <select
                className="w-[100%] bg-[#F0F2F5] py-[10px] md:py-[14px] outline-none"
                name="outcall_overnight"
                id="outcall_overnight"
                value={formData.outcall_overnight}
                onChange={handleChange}
              >
                <option value="">Choose here</option>
                <option>1</option>
                <option>10</option>
                <option>100</option>
                <option>1000</option>
                <option>10000</option>
                <option>100000</option>
                <option>1000000</option>
                <option>15</option>
                <option>150</option>
                <option>1500</option>
                <option>15000</option>
                <option>150000</option>
                <option>1500000</option>
                <option>2</option>
                <option>20</option>
                <option>200</option>
                <option>2000</option>
                <option>20000</option>
                <option>200000</option>
                <option>2000000</option>
                <option>25</option>
                <option>250</option>
                <option>2500</option>
                <option>25000</option>
                <option>250000</option>
                <option>2500000</option>
                <option>3</option>
                <option>30</option>
                <option>300</option>
                <option>3000</option>
                <option>30000</option>
                <option>300000</option>
                <option>3000000</option>
                <option>35</option>
                <option>350</option>
                <option>3500</option>
                <option>35000</option>
                <option>350000</option>
                <option>3500000</option>
                <option>4</option>
                <option>40</option>
                <option>400</option>
                <option>4000</option>
                <option>40000</option>
                <option>400000</option>
                <option>4000000</option>
                <option>45</option>
                <option>450</option>
                <option>4500</option>
                <option>45000</option>
                <option>450000</option>
                <option>4500000</option>
                <option>5</option>
                <option>50</option>
                <option>500</option>
                <option>5000</option>
                <option>50000</option>
                <option>500000</option>
                <option>5000000</option>
                <option>55</option>
                <option>550</option>
                <option>5500</option>
                <option>55000</option>
                <option>550000</option>
                <option>5500000</option>
                <option>6</option>
                <option>60</option>
                <option>600</option>
                <option>6000</option>
                <option>60000</option>
                <option>600000</option>
                <option>6000000</option>
                <option>65</option>
                <option>650</option>
                <option>6500</option>
                <option>65000</option>
                <option>650000</option>
                <option>6500000</option>
                <option>7</option>
                <option>70</option>
                <option>700</option>
                <option>7000</option>
                <option>70000</option>
                <option>700000</option>
                <option>7000000</option>
                <option>75</option>
                <option>750</option>
                <option>7500</option>
                <option>75000</option>
                <option>750000</option>
                <option>7500000</option>
                <option>8</option>
                <option>80</option>
                <option>800</option>
                <option>8000</option>
                <option>80000</option>
                <option>800000</option>
                <option>8000000</option>
                <option>85</option>
                <option>850</option>
                <option>8500</option>
                <option>85000</option>
                <option>850000</option>
                <option>8500000</option>
                <option>9</option>
                <option>90</option>
                <option>900</option>
                <option>9000</option>
                <option>90000</option>
                <option>900000</option>
                <option>9000000</option>
                <option>95</option>
                <option>950</option>
                <option>9500</option>
                <option>95000</option>
                <option>950000</option>
                <option>9500000</option>
              </select>
            </div>
          </label>
          <label htmlFor="outcall_weekend">
            <p className="py-2 font-semibold">Weekend Rate</p>
            <div className=" placeholder-[#102127] bg-[#F0F2F5] text-[#102127] rounded-xl outline-none px-4">
              <select
                className="w-[100%] bg-[#F0F2F5] py-[10px] md:py-[14px] outline-none"
                name="outcall_weekend"
                id="outcall_weekend"
                value={formData.outcall_weekend}
                onChange={handleChange}
              >
                <option value="">Choose here</option>
                <option>1</option>
                <option>10</option>
                <option>100</option>
                <option>1000</option>
                <option>10000</option>
                <option>100000</option>
                <option>1000000</option>
                <option>15</option>
                <option>150</option>
                <option>1500</option>
                <option>15000</option>
                <option>150000</option>
                <option>1500000</option>
                <option>2</option>
                <option>20</option>
                <option>200</option>
                <option>2000</option>
                <option>20000</option>
                <option>200000</option>
                <option>2000000</option>
                <option>25</option>
                <option>250</option>
                <option>2500</option>
                <option>25000</option>
                <option>250000</option>
                <option>2500000</option>
                <option>3</option>
                <option>30</option>
                <option>300</option>
                <option>3000</option>
                <option>30000</option>
                <option>300000</option>
                <option>3000000</option>
                <option>35</option>
                <option>350</option>
                <option>3500</option>
                <option>35000</option>
                <option>350000</option>
                <option>3500000</option>
                <option>4</option>
                <option>40</option>
                <option>400</option>
                <option>4000</option>
                <option>40000</option>
                <option>400000</option>
                <option>4000000</option>
                <option>45</option>
                <option>450</option>
                <option>4500</option>
                <option>45000</option>
                <option>450000</option>
                <option>4500000</option>
                <option>5</option>
                <option>50</option>
                <option>500</option>
                <option>5000</option>
                <option>50000</option>
                <option>500000</option>
                <option>5000000</option>
                <option>55</option>
                <option>550</option>
                <option>5500</option>
                <option>55000</option>
                <option>550000</option>
                <option>5500000</option>
                <option>6</option>
                <option>60</option>
                <option>600</option>
                <option>6000</option>
                <option>60000</option>
                <option>600000</option>
                <option>6000000</option>
                <option>65</option>
                <option>650</option>
                <option>6500</option>
                <option>65000</option>
                <option>650000</option>
                <option>6500000</option>
                <option>7</option>
                <option>70</option>
                <option>700</option>
                <option>7000</option>
                <option>70000</option>
                <option>700000</option>
                <option>7000000</option>
                <option>75</option>
                <option>750</option>
                <option>7500</option>
                <option>75000</option>
                <option>750000</option>
                <option>7500000</option>
                <option>8</option>
                <option>80</option>
                <option>800</option>
                <option>8000</option>
                <option>80000</option>
                <option>800000</option>
                <option>8000000</option>
                <option>85</option>
                <option>850</option>
                <option>8500</option>
                <option>85000</option>
                <option>850000</option>
                <option>8500000</option>
                <option>9</option>
                <option>90</option>
                <option>900</option>
                <option>9000</option>
                <option>90000</option>
                <option>900000</option>
                <option>9000000</option>
                <option>95</option>
                <option>950</option>
                <option>9500</option>
                <option>95000</option>
                <option>950000</option>
                <option>9500000</option>
              </select>
            </div>
          </label>
        </div>

        <div>
          <h2 className="pb-3 pt-6 font-semibold text-[18px] text-white">
            Incall Rates
          </h2>
          <div className="grid text-white md:grid-cols-3 gap-5">
            <label htmlFor="incall_short_time">
              <p className="py-2 font-semibold">Hourly Rate</p>
              <div className=" placeholder-[#102127] bg-[#F0F2F5] text-[#102127] rounded-xl outline-none px-4">
                <select
                  className="w-[100%] bg-[#F0F2F5] py-[10px] md:py-[14px] outline-none"
                  name="incall_short_time"
                  id="incall_short_time"
                  value={formData.incall_short_time}
                  onChange={handleChange}
                >
                  <option value="">Choose here</option>
                  <option>1</option>
                  <option>10</option>
                  <option>100</option>
                  <option>1000</option>
                  <option>10000</option>
                  <option>100000</option>
                  <option>1000000</option>
                  <option>15</option>
                  <option>150</option>
                  <option>1500</option>
                  <option>15000</option>
                  <option>150000</option>
                  <option>1500000</option>
                  <option>2</option>
                  <option>20</option>
                  <option>200</option>
                  <option>2000</option>
                  <option>20000</option>
                  <option>200000</option>
                  <option>2000000</option>
                  <option>25</option>
                  <option>250</option>
                  <option>2500</option>
                  <option>25000</option>
                  <option>250000</option>
                  <option>2500000</option>
                  <option>3</option>
                  <option>30</option>
                  <option>300</option>
                  <option>3000</option>
                  <option>30000</option>
                  <option>300000</option>
                  <option>3000000</option>
                  <option>35</option>
                  <option>350</option>
                  <option>3500</option>
                  <option>35000</option>
                  <option>350000</option>
                  <option>3500000</option>
                  <option>4</option>
                  <option>40</option>
                  <option>400</option>
                  <option>4000</option>
                  <option>40000</option>
                  <option>400000</option>
                  <option>4000000</option>
                  <option>45</option>
                  <option>450</option>
                  <option>4500</option>
                  <option>45000</option>
                  <option>450000</option>
                  <option>4500000</option>
                  <option>5</option>
                  <option>50</option>
                  <option>500</option>
                  <option>5000</option>
                  <option>50000</option>
                  <option>500000</option>
                  <option>5000000</option>
                  <option>55</option>
                  <option>550</option>
                  <option>5500</option>
                  <option>55000</option>
                  <option>550000</option>
                  <option>5500000</option>
                  <option>6</option>
                  <option>60</option>
                  <option>600</option>
                  <option>6000</option>
                  <option>60000</option>
                  <option>600000</option>
                  <option>6000000</option>
                  <option>65</option>
                  <option>650</option>
                  <option>6500</option>
                  <option>65000</option>
                  <option>650000</option>
                  <option>6500000</option>
                  <option>7</option>
                  <option>70</option>
                  <option>700</option>
                  <option>7000</option>
                  <option>70000</option>
                  <option>700000</option>
                  <option>7000000</option>
                  <option>75</option>
                  <option>750</option>
                  <option>7500</option>
                  <option>75000</option>
                  <option>750000</option>
                  <option>7500000</option>
                  <option>8</option>
                  <option>80</option>
                  <option>800</option>
                  <option>8000</option>
                  <option>80000</option>
                  <option>800000</option>
                  <option>8000000</option>
                  <option>85</option>
                  <option>850</option>
                  <option>8500</option>
                  <option>85000</option>
                  <option>850000</option>
                  <option>8500000</option>
                  <option>9</option>
                  <option>90</option>
                  <option>900</option>
                  <option>9000</option>
                  <option>90000</option>
                  <option>900000</option>
                  <option>9000000</option>
                  <option>95</option>
                  <option>950</option>
                  <option>9500</option>
                  <option>95000</option>
                  <option>950000</option>
                  <option>9500000</option>
                </select>
              </div>
            </label>
            <label htmlFor="incall_overnight">
              <p className="py-2 font-semibold">One Night</p>
              <div className=" placeholder-[#102127] bg-[#F0F2F5] text-[#102127] rounded-xl outline-none px-4">
                <select
                  className="w-[100%] bg-[#F0F2F5] py-[10px] md:py-[14px] outline-none"
                  name="incall_overnight"
                  id="incall_overnight"
                  value={formData.incall_overnight}
                  onChange={handleChange}
                >
                  <option value="">Choose here</option>
                  <option>1</option>
                  <option>10</option>
                  <option>100</option>
                  <option>1000</option>
                  <option>10000</option>
                  <option>100000</option>
                  <option>1000000</option>
                  <option>15</option>
                  <option>150</option>
                  <option>1500</option>
                  <option>15000</option>
                  <option>150000</option>
                  <option>1500000</option>
                  <option>2</option>
                  <option>20</option>
                  <option>200</option>
                  <option>2000</option>
                  <option>20000</option>
                  <option>200000</option>
                  <option>2000000</option>
                  <option>25</option>
                  <option>250</option>
                  <option>2500</option>
                  <option>25000</option>
                  <option>250000</option>
                  <option>2500000</option>
                  <option>3</option>
                  <option>30</option>
                  <option>300</option>
                  <option>3000</option>
                  <option>30000</option>
                  <option>300000</option>
                  <option>3000000</option>
                  <option>35</option>
                  <option>350</option>
                  <option>3500</option>
                  <option>35000</option>
                  <option>350000</option>
                  <option>3500000</option>
                  <option>4</option>
                  <option>40</option>
                  <option>400</option>
                  <option>4000</option>
                  <option>40000</option>
                  <option>400000</option>
                  <option>4000000</option>
                  <option>45</option>
                  <option>450</option>
                  <option>4500</option>
                  <option>45000</option>
                  <option>450000</option>
                  <option>4500000</option>
                  <option>5</option>
                  <option>50</option>
                  <option>500</option>
                  <option>5000</option>
                  <option>50000</option>
                  <option>500000</option>
                  <option>5000000</option>
                  <option>55</option>
                  <option>550</option>
                  <option>5500</option>
                  <option>55000</option>
                  <option>550000</option>
                  <option>5500000</option>
                  <option>6</option>
                  <option>60</option>
                  <option>600</option>
                  <option>6000</option>
                  <option>60000</option>
                  <option>600000</option>
                  <option>6000000</option>
                  <option>65</option>
                  <option>650</option>
                  <option>6500</option>
                  <option>65000</option>
                  <option>650000</option>
                  <option>6500000</option>
                  <option>7</option>
                  <option>70</option>
                  <option>700</option>
                  <option>7000</option>
                  <option>70000</option>
                  <option>700000</option>
                  <option>7000000</option>
                  <option>75</option>
                  <option>750</option>
                  <option>7500</option>
                  <option>75000</option>
                  <option>750000</option>
                  <option>7500000</option>
                  <option>8</option>
                  <option>80</option>
                  <option>800</option>
                  <option>8000</option>
                  <option>80000</option>
                  <option>800000</option>
                  <option>8000000</option>
                  <option>85</option>
                  <option>850</option>
                  <option>8500</option>
                  <option>85000</option>
                  <option>850000</option>
                  <option>8500000</option>
                  <option>9</option>
                  <option>90</option>
                  <option>900</option>
                  <option>9000</option>
                  <option>90000</option>
                  <option>900000</option>
                  <option>9000000</option>
                  <option>95</option>
                  <option>950</option>
                  <option>9500</option>
                  <option>95000</option>
                  <option>950000</option>
                  <option>9500000</option>
                </select>
              </div>
            </label>
            <label htmlFor="incall_weekend">
              <p className="py-2 font-semibold">Weekend Rate</p>
              <div className=" placeholder-[#102127] bg-[#F0F2F5] text-[#102127] rounded-xl outline-none px-4">
                <select
                  className="w-[100%] bg-[#F0F2F5] py-[10px] md:py-[14px] outline-none"
                  name="incall_weekend"
                  id="incall_weekend"
                  value={formData.incall_weekend}
                  onChange={handleChange}
                >
                  <option value="">Choose here</option>
                  <option>1</option>
                  <option>10</option>
                  <option>100</option>
                  <option>1000</option>
                  <option>10000</option>
                  <option>100000</option>
                  <option>1000000</option>
                  <option>15</option>
                  <option>150</option>
                  <option>1500</option>
                  <option>15000</option>
                  <option>150000</option>
                  <option>1500000</option>
                  <option>2</option>
                  <option>20</option>
                  <option>200</option>
                  <option>2000</option>
                  <option>20000</option>
                  <option>200000</option>
                  <option>2000000</option>
                  <option>25</option>
                  <option>250</option>
                  <option>2500</option>
                  <option>25000</option>
                  <option>250000</option>
                  <option>2500000</option>
                  <option>3</option>
                  <option>30</option>
                  <option>300</option>
                  <option>3000</option>
                  <option>30000</option>
                  <option>300000</option>
                  <option>3000000</option>
                  <option>35</option>
                  <option>350</option>
                  <option>3500</option>
                  <option>35000</option>
                  <option>350000</option>
                  <option>3500000</option>
                  <option>4</option>
                  <option>40</option>
                  <option>400</option>
                  <option>4000</option>
                  <option>40000</option>
                  <option>400000</option>
                  <option>4000000</option>
                  <option>45</option>
                  <option>450</option>
                  <option>4500</option>
                  <option>45000</option>
                  <option>450000</option>
                  <option>4500000</option>
                  <option>5</option>
                  <option>50</option>
                  <option>500</option>
                  <option>5000</option>
                  <option>50000</option>
                  <option>500000</option>
                  <option>5000000</option>
                  <option>55</option>
                  <option>550</option>
                  <option>5500</option>
                  <option>55000</option>
                  <option>550000</option>
                  <option>5500000</option>
                  <option>6</option>
                  <option>60</option>
                  <option>600</option>
                  <option>6000</option>
                  <option>60000</option>
                  <option>600000</option>
                  <option>6000000</option>
                  <option>65</option>
                  <option>650</option>
                  <option>6500</option>
                  <option>65000</option>
                  <option>650000</option>
                  <option>6500000</option>
                  <option>7</option>
                  <option>70</option>
                  <option>700</option>
                  <option>7000</option>
                  <option>70000</option>
                  <option>700000</option>
                  <option>7000000</option>
                  <option>75</option>
                  <option>750</option>
                  <option>7500</option>
                  <option>75000</option>
                  <option>750000</option>
                  <option>7500000</option>
                  <option>8</option>
                  <option>80</option>
                  <option>800</option>
                  <option>8000</option>
                  <option>80000</option>
                  <option>800000</option>
                  <option>8000000</option>
                  <option>85</option>
                  <option>850</option>
                  <option>8500</option>
                  <option>85000</option>
                  <option>850000</option>
                  <option>8500000</option>
                  <option>9</option>
                  <option>90</option>
                  <option>900</option>
                  <option>9000</option>
                  <option>90000</option>
                  <option>900000</option>
                  <option>9000000</option>
                  <option>95</option>
                  <option>950</option>
                  <option>9500</option>
                  <option>95000</option>
                  <option>950000</option>
                  <option>9500000</option>
                </select>
              </div>
            </label>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EscortRateEdit;
